# Generated by Django 3.2.4 on 2021-08-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_addstudent_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.addbook'),
        ),
    ]
