# Generated by Django 3.2.4 on 2021-09-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_addstudent_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='book',
        ),
        migrations.AddField(
            model_name='addbook',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.addstudent'),
        ),
    ]
