# Generated by Django 3.2.4 on 2021-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_book_addbook_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='des',
            field=models.CharField(default='no des', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addbook',
            name='genres',
            field=models.CharField(default='no genres', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addbook',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='address',
            field=models.CharField(default='no address', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='branch',
            field=models.CharField(default='no branch', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='mobile',
            field=models.CharField(default='no mobile', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='sem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
