# Generated by Django 3.2.4 on 2021-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210901_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
