# Generated by Django 3.2.4 on 2021-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_addbook_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='email',
            field=models.EmailField(default='no email', max_length=40),
            preserve_default=False,
        ),
    ]
