# Generated by Django 3.2.4 on 2021-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_addstudent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
