# Generated by Django 3.2.4 on 2021-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_addbook_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='language',
            field=models.CharField(default='DND', max_length=20),
            preserve_default=False,
        ),
    ]
